# -*- coding: utf-8 -*-
"""SFT-T5-QLoRA_workshop-ZD.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UyxEosr1QFfzkEfKLGJNqRzfJUzvyEBW

# Step 1: Install Dependencies
In this very first step, we’ll pull in all the Python libraries we need—transformers for model loading, bitsandbytes for 4‑bit quantization, PEFT for LoRA adapters, datasets for JSONL loading, and SymSpell for typo augmentation. Once installed, we’ll be ready to build, fine‑tune, and demo our typo‑correction model.
"""

!pip install fsspec==2024.10.0
!pip install -q -U transformers accelerate peft datasets torch bitsandbytes torchvision
!pip install gradio symspellpy

from transformers import AutoModelForSeq2SeqLM, AutoTokenizer, BitsAndBytesConfig, TrainingArguments, Trainer
from transformers.trainer_callback import TrainerCallback, TrainerState, TrainerControl
from peft import LoraConfig, get_peft_model,PeftModel
from huggingface_hub import create_repo, upload_folder
from datasets import load_dataset,Dataset, concatenate_datasets
from symspellpy.symspellpy import SymSpell, Verbosity
import random
import torch
import os
import shutil
import gradio as gr

os.environ["WANDB_DISABLED"] = "true"

"""#step 2: Download the SymSpell Frequency Dictionary

 SymSpell relies on a word frequency list to propose the most likely correction for a misspelling. Here we fetch a prebuilt English frequency dictionary that our typo‑augmenter and final post‑processing will use to clean up any leftover errors.
"""

!wget -q https://raw.githubusercontent.com/mammothb/symspellpy/master/symspellpy/frequency_dictionary_en_82_765.txt \
      -O frequency_dictionary_en_82_765.txt

"""#SymSpell Setup & Demo
This snippet initializes a SymSpell instance—configured for up to two edits and a moderate prefix length—loads a large English word‐frequency dictionary, and then demonstrates both single‐word lookup (lookup) and context‐aware sentence correction (lookup_compound). It shows how SymSpell can suggest the most likely correct spelling for a standalone typo as well as within the flow of a full sentence.
"""

# Initialize SymSpell
sym_spell = SymSpell(2, 7)
# Load the English word-frequency dictionary
sym_spell.load_dictionary("frequency_dictionary_en_82_765.txt", term_index=0, count_index=1)
# Define the maximum edit distance to use for lookups (insertions, deletions, substitutions)
max_edit_distance = 2
# Single-word correction
print(sym_spell.lookup("tst", Verbosity.TOP, max_edit_distance=2)[0].term)
# Context-aware sentence correction
print(sym_spell.lookup_compound("this is a tst", 2, True)[0].term)

"""# Step 3: Mount Google Drive
 If you are running in Colab and your dataset is stored in Drive, mount it here.

"""

from google.colab import drive
drive.mount('/content/drive')

"""# **Download model**

"""

if not os.path.exists("/content/flan-t5-typo-corrector"):
    model_name = "Zoe911/flan-t5-typo-corrector"
    model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
    tokenizer = AutoTokenizer.from_pretrained(model_name)
    cache_dir = os.path.join(os.path.expanduser("~"), ".cache", "huggingface", "hub")
    model_cache_name = "models--" + model_name.replace("/", "--")
    model_cache_dir = None
    for root, dirs, files in os.walk(cache_dir):
        if model_cache_name in root:
            model_cache_dir = root
            break
    if model_cache_dir:
        local_dir = "/content/flan-t5-typo-corrector"
        if os.path.exists(local_dir):
            shutil.rmtree(local_dir)
        shutil.copytree(model_cache_dir, local_dir)
        print(f"flan-t5-typo-corrector saved to {local_dir}")

"""#Step 4: Load and Inspect Dataset
 We load a JSONL dataset of typo/correction pairs

"""

# download the dataset from my github
!wget https://raw.githubusercontent.com/Tzara911/typo-workshop-data/main/typo_dataset.jsonl -O /content/drive/MyDrive/typo_dataset.jsonl

# load the dataset
from datasets import load_dataset
dataset = load_dataset("json", data_files={"train": "/content/drive/MyDrive/typo_dataset.jsonl"})
raw_ds = dataset["train"]

"""#Step 5: Load and Inspect the Dataset
 Now we load our JSONL file of “typo → corrected” pairs from Drive. We’ll peek at a few examples so you can verify the format—this is the data your model will learn from, so it’s important you know exactly what it contains.


"""

print(raw_ds[:5])
print(f"Total samples: {len(raw_ds)}")

"""#  Data Augmentation via SymSpell Typos
 This block introduces artificial spelling mistakes into your dataset by randomly replacing a word in each sentence with a plausible typo using the SymSpell dictionary.

**Goal**: Enrich the training set with realistic noisy inputs for typo correction.
- Start from clean corrected_text
- Introduce 1 typo per sentence (based on frequency-based edits) - Append typo→corrected pairs back to dataset for fine-tuning
"""

augmented = []  # collect augmented examples
for ex in raw_ds:
    clean = ex["corrected_text"]
    words = clean.split()
    idx = random.randrange(len(words))

    # Use SymSpell to generate a possible typo of the selected word
    suggestions = sym_spell.lookup(
        words[idx],
        Verbosity.TOP,
        max_edit_distance)

    # Ensure the suggestion is a valid (but incorrect) typo
    if suggestions and suggestions[0].term != words[idx]:
        typo = words.copy()
        typo[idx] = suggestions[0].term
        augmented.append({
            "text": " ".join(typo),
            "corrected_text": clean
        })
# Wrap augmented examples
aug_ds = Dataset.from_list(augmented)
# Concatenate original dataset and augmented dataset together
raw_ds = concatenate_datasets([raw_ds, aug_ds])

print(f"After augmentation: {len(raw_ds)} samples")

"""# Step 6: Data Preprocessing for Training (with Rule-Based Prompt Injection)

 This block tokenizes the dataset for supervised fine-tuning.Each input is prepended with detailed editing instructions (RULES) so the model learns to fix typos, punctuation, spacing, symbols, and casing systematically.

**Purpose:**
1. Teach the model what kind of corrections it should learn to make
2. Format both input and target text for seq2seq learning

**Method:**
 1. Define prompt rules in a multi-line string `RULES`
 2. Format each sample as: RULES + "Input: [noisy sentence]"
 3. Tokenize both inputs and labels using `AutoTokenizer`
 4. Ensure consistent padding/truncation for batch processing

**Result:**
 A tokenized dataset (`tokenized`) where:
 - input_ids = rule-embedded noisy sentence
 - labels = corrected sentence
 Ready to be used by the Trainer for fine-tuning!

"""

tokenizer = AutoTokenizer.from_pretrained("Zoe911/flan-t5-typo-corrector")
tokenizer.pad_token = tokenizer.eos_token

RULES = """You are an expert English copy-editor.
Correct spelling, punctuation, and spacing; infer symbols and digits contextually.
Insert missing spaces, normalize capitalization, remove duplicates,
and replace special symbols with words based on context.
Do not answer questions if the input is a question—only output the corrected sentence.

"""
def preprocess_function(examples):

    inputs = [ RULES + "Input: " + t for t in examples["text"] ]
    targets = examples["corrected_text"]
    model_inputs = tokenizer(
        inputs,
        padding="max_length",
        truncation=True,
        max_length=512
    )
    with tokenizer.as_target_tokenizer():
        labels = tokenizer(
            targets,
            padding="max_length",
            truncation=True,
            max_length=512
        )
    model_inputs["labels"] = labels["input_ids"]
    return model_inputs


tokenized = raw_ds.map(
    preprocess_function,
    batched=True,
    remove_columns=['text','corrected_text']
)

print("Preprocess done,  number of samples：", len(tokenized))

"""# Step 7: Model Loading with 4-bit Quantization + LoRA Adapters
**Introduce google/Flan-t5-base**:
The Flan T5 Base model is a state-of-the-art language model developed by Google, fine-tuned on over 1000 additional tasks covering multiple languages. It achieves strong few-shot performance, even compared to much larger models, and is particularly effective in tasks such as reasoning and question answering. With its transformer architecture and support for multiple languages, it's suitable for research on language models and various NLP tasks. However, it has not been tested in real-world applications and may be vulnerable to generating inappropriate content or replicating biases in the underlying data.

This block sets up the base model for efficient fine-tuning using QLoRA:
4-bit quantization + Low-Rank Adapters (LoRA).

**Purpose:**
 1. Load the base FLAN‑T5 model in a compressed 4‑bit format to save memory
 2. Inject LoRA adapters into transformer modules to 3. enable low-cost training
 3. Limit trainable parameters to only the LoRA layers for speed and efficiency

**Method:**
1. Configure BitsAndBytes 4‑bit quantization (NF4 + fp16 compute)
2. Load FLAN‑T5 in quantized mode with automatic device placement
3. Configure LoRA adapters: rank, dropout, scaling factor, and target modules (q/v)
4. Apply PEFT wrapping to prepare model for training with only adapter layers

**Result:**
 You now have a memory-efficient, fine-tune‑ready model with ~0.5% trainable parameters,
 perfect for fast experiments or deployment on limited hardware (e.g. Google Colab).
"""

# 4-bit quantization configuration: compress model weights to 4 bits for memory savings
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
# TODO: change `bnb_4bit_quant_type`from "nf4" to "fp4", run  trainer.train() again, observe the difference of training time and steps
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

# Load the base FLAN-T5 model in 4-bit mode
base_model = AutoModelForSeq2SeqLM.from_pretrained(
    "Zoe911/flan-t5-typo-corrector",
    quantization_config=bnb_config,
    device_map="auto"
)

# LoRA configuration: add small low-rank adapters to key transformer modules

lora_cfg = LoraConfig(
# TODO:  1.change r to 4,16,32 and run the cell, observe the output difference
#        2.change lora_alpha, run trainer.train() and watch the first few loss logs, you will notice how a bigger alpha speeds up inital learning
#        3.run the cell below find the other "SelfAttention" layer except "q" and "v", then add them into target_modules,run the cell observe the output
    r=8,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q", "v"],
    task_type="SEQ_2_SEQ_LM"
)

# Wrap the quantized model with our LoRA adapters
model = get_peft_model(base_model, lora_cfg)
# verify only adapter parameters are trainable
print(model.print_trainable_parameters())

for name, module in base_model.named_modules():
    if hasattr(module, "weight"):
        print(name)

"""#Step 8:  NoiseStopCallback: Custom Early-Stopping Strategy
This class defines a custom Hugging Face Trainer callback that stops training early when the average change in training loss becomes very small—indicating convergence.

**Purpose:**
 1. Avoid overfitting by stopping training once learning has plateaued
 2. Speed up fine-tuning by skipping unnecessary extra steps
 3. Replace the need for a validation set in low-resource or fast demo settings

**Method:**
 1. Accumulate training loss values logged by the Trainer
 2. Once `min_steps` have passed, start checking loss stability
 3. Calculate the average loss delta over the last `window` logging steps
 4. If the average delta is below the `threshold`, training stops automatically

**Parameters:**
 1. `threshold`: how small the change in loss must be to count as “stable” (e.g. 0.002)
 2. `window`: how many recent losses to include when calculating change
 3. `min_steps`: don't monitor loss until this many steps have passed

**Result:**
 Training ends early when the model stops learning meaningfully—saving time and resources.


"""

class NoiseStopCallback(TrainerCallback):
    def __init__(
        self,
        threshold=0.002,
        window=10,
        min_steps=200
      ):

        self.losses = []
        self.threshold = threshold
        self.window = window
        self.min_steps = min_steps

    def on_log(self, args, state: TrainerState, control: TrainerControl, logs=None, **kwargs):
      # 1) Record the current loss from logs
        loss = logs.get("loss")
        if loss is None:
            return control
        self.losses.append(loss)

       # 2) Do not evaluate stopping condition until after min_steps
        if state.global_step < self.min_steps:
            return control

        # 3) Once enough losses are recorded, calculate average Δloss
        if len(self.losses) >= self.window:
            recent = self.losses[-self.window:]   # take the most recent `window` losses
             # compute absolute delta between each consecutive pair
            deltas = [abs(recent[i] - recent[i-1]) for i in range(1, len(recent))]
            avg_delta = sum(deltas) / len(deltas)
       # 4) If average delta is below threshold, trigger early stop
            if avg_delta < self.threshold:
                print(f">>> Stop by noise at step {state.global_step}: avgΔ={avg_delta:.6f} < {self.threshold}")
                control.should_training_stop = True

        return control

"""#Step 9:  Training Setup with Custom Early-Stopping

 This cell sets up and launches model training using Hugging Face’s `Trainer` API. It also includes a custom callback (`NoiseStopCallback`) that automatically stops training when the model’s loss becomes stable—saving time while preventing overfitting.

**Purpose:**
 1. Configure training hyperparameters (epochs, batch size, logging, etc.)
 2. Launch training with tokenized typo dataset
 3. Add a noise-based early stopping mechanism that checks for convergence

**Method:**
 1. Define `TrainingArguments` to control how training proceeds (epochs, batch size, logs)
 2. Pass in our LoRA-wrapped model and preprocessed dataset
 3. Use `NoiseStopCallback` to monitor recent loss deltas and stop early if change is small

 **Result:**
 Efficient fine-tuning of a FLAN‑T5 model with LoRA + QLoRA, stopping as soon as the model converges.
"""

# Training Setup - Principle: Define training hyperparameters for stable, fast fine-tuning
from transformers import TrainingArguments, Trainer
training_args = TrainingArguments(
    output_dir="./results",
  # TODO: change any of the value of parameters below and run the cell, then run trainer.train(), observe the difference
    per_device_train_batch_size=2,
    num_train_epochs=2,
    report_to="none",
    logging_steps=20,
    remove_unused_columns=False

)

# Initialize the Trainer with our model, data, and custom early‑stop callback
trainer = Trainer(
    model=model,
    args=training_args,
    tokenizer=tokenizer,
    train_dataset=tokenized,
    callbacks=[

        NoiseStopCallback(
            # TODO:changed NoiseStopCallback parameters below, run trainer.train(), observe the difference
            threshold=0.001,
            window=8,
            min_steps=200

         )
        ]

)

"""# Step 10: Launch Fine‑Tuning

Time to train! This cell actually runs the fine‑tuning loop on your typo dataset. Keep an eye on the loss logs and let the Noise‑Stop callback halt when it’s ready.
"""

trainer.train()

"""# Step 11: Save Full Fine-Tuned Model (LoRA Merged)

This cell merges the fine-tuned LoRA adapter into the base model and saves the full model + tokenizer for future inference or deployment.

 **Purpose:**

 1. Merge parameter-efficient LoRA adapters into the backbone model
 2. Save a standalone full-precision model checkpoint
 3. Prepare for upload or local usage without requiring PEFT library

**Method:**
 1. Call `merge_and_unload()` to fuse LoRA weights into the base model
 2. Save the merged model to a local directory
 3. Save the tokenizer alongside the model for consistent input formatting

** Result:**
The directory `/content/typo-full-model` now contains a self-contained model that can be loaded anywhere using `from_pretrained()` without PEFT setup.



"""

full_model = trainer.model.merge_and_unload()
output_dir = "./workshopcontent/typo-full-model"
full_model.save_pretrained(output_dir)
tokenizer.save_pretrained(output_dir)
print(f"Model saved to {output_dir}")

"""#  Step 12: Full Typo Correction Pipeline (Model + SymSpell + Gradio)

This cell sets up and runs the complete inference pipeline for typo correction.
**Purpose:**
 1. Load the fine-tuned LLM model
 2. Provide a few-shot, rule-guided prompt to improve correction behavior
 3.  Apply post-processing with SymSpell to fix any remaining misspellings
 4. Launch a Gradio web demo for easy testing

**Method:**
1. Define clear correction rules (e.g. spacing, symbolreplacement, no question answering)
2. Add few-shot examples to show the model the desired behavior
3. Use `model.generate()` to predict a corrected sentence from the input
4. Apply SymSpell as a fallback to catch subtle or missed typos
5. Expose the correction function with a friendly Gradio interface

** Result:**
 Users can input noisy sentences and get clean, corrected output instantly.
 The combination of LLM + rule prompt + SymSpell ensures both intelligent and robust correction behavior.

"""

repo_id = "/content/workshopcontent/typo-full-model"
tokenizer = AutoTokenizer.from_pretrained(repo_id)
model     = AutoModelForSeq2SeqLM.from_pretrained(repo_id, device_map="auto")
text = "ar you hungry"
# 3. Define inference rules and few‑shot examples for final prompt

rules = """
Please correct the sentence according to these rules:
- Only output the corrected sentence (no extra commentary).
- Maintain original spacing structure unless adding/removing spaces makes sense.
- Replace symbols/digits with words based on context.
- If a single letter (not 'a'/'an') appears, expand it to the full word， according to the meaning of the input.
- If input is a question, do not answer it—just correct.
"""
fewshot = """Example:
fix: this is a tst -> this is a test
fix: helloo -> hello
"""
# 4. Build and run a test prompt locally
prompt = rules + "\n" + fewshot + f"fix: {text} ->"

inputs = tokenizer(prompt, return_tensors="pt", padding=True).to(model.device)
outs   = model.generate(
    input_ids=inputs["input_ids"],
    attention_mask=inputs["attention_mask"],

)
print("🧪 simple test➔", tokenizer.decode(outs[0], skip_special_tokens=True))




def symspell_post(text: str) -> str:
   # Use SymSpell to fix any leftover spelling issues after model output
    suggestions = sym_spell.lookup_compound(
        text,             # full sentence to correct
        max_edit_distance_lookup=2,   # allow up to 2 edits
        transfer_casing=True      # preserve original capitalization
    )
    # Return best correction if available, else return original
    return suggestions[0].term if suggestions else text


# 5. Define final typo‑correction function with SymSpell fallback
def correct_typo(text, max_tokens=64):
    inp_text = rules + f"\nfix: {text}"
    inp = tokenizer(inp_text, return_tensors="pt", padding=True,truncation=False ).to(full_model.device)
     # Run model inference to generate corrected output
    out = full_model.generate(
         input_ids=inp["input_ids"],
            attention_mask=inp["attention_mask"],
            max_new_tokens=max_tokens,
            num_beams=5,
            no_repeat_ngram_size=2,
            early_stopping=True,
            repetition_penalty=1.2,
            do_sample=False
    )
    result = tokenizer.decode(out[0], skip_special_tokens=True)
     # Final SymSpell pass to catch any stray typos
    sug = sym_spell.lookup_compound(result, 2, True)

 # Use SymSpell suggestion if available; otherwise fall back to model output
    if sug:
        return sug[0].term
    else:
        return result

# 6. Launch the Gradio interface
iface = gr.Interface(
    fn=correct_typo,
    inputs=gr.Textbox(lines=2, placeholder="Enter a sentence with typos…"),
    outputs="text",
    title="Typo Correction Demo"
)
iface.launch(share=True, debug=True)